-- V1: schema base do apurador.
--
-- Migracao versionada em vez de ddl-auto. Em sistema fiscal o schema precisa de
-- historico auditavel pelo mesmo motivo que as tabelas de aliquota precisam:
-- para explicar, meses depois, como o banco estava quando uma guia foi emitida.
--
-- SQL escrito de forma portavel: roda em PostgreSQL (producao) e em H2 no modo
-- PostgreSQL (testes de integracao), sem dialeto exclusivo de nenhum dos dois.

CREATE TABLE empresa (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj                   VARCHAR(14)  NOT NULL UNIQUE,
    razao_social           VARCHAR(255) NOT NULL,
    anexo                  VARCHAR(20)  NOT NULL,
    inicio_atividade_ano   INTEGER      NOT NULL,
    inicio_atividade_mes   INTEGER      NOT NULL
);

CREATE TABLE faixa_tabela (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anexo            VARCHAR(20)    NOT NULL,
    faixa            INTEGER        NOT NULL,
    limite_inferior  NUMERIC(15, 2) NOT NULL,
    limite_superior  NUMERIC(15, 2) NOT NULL,
    aliquota_nominal NUMERIC(10, 6) NOT NULL,
    parcela_deduzir  NUMERIC(15, 2) NOT NULL,
    vigencia_inicio  DATE           NOT NULL,
    -- NULL = vigente por prazo indeterminado
    vigencia_fim     DATE,
    fonte            VARCHAR(200)
);

-- A consulta quente do sistema e "faixas do anexo X vigentes na data Y".
CREATE INDEX idx_faixa_anexo_vigencia ON faixa_tabela (anexo, vigencia_inicio, vigencia_fim);

CREATE TABLE receita (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT         NOT NULL REFERENCES empresa (id),
    ano        INTEGER        NOT NULL,
    mes        INTEGER        NOT NULL,
    valor      NUMERIC(15, 2) NOT NULL,
    -- Uma empresa tem no maximo um lancamento por competencia. A regra vive no
    -- banco porque e o unico lugar que a garante sob concorrencia.
    CONSTRAINT uk_receita_empresa_competencia UNIQUE (empresa_id, ano, mes)
);

CREATE TABLE apuracao (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id              BIGINT          NOT NULL REFERENCES empresa (id),
    ano                     INTEGER         NOT NULL,
    mes                     INTEGER         NOT NULL,
    anexo                   VARCHAR(20)     NOT NULL,
    receita_bruta_mes       NUMERIC(15, 2)  NOT NULL,
    rbt12                   NUMERIC(15, 2)  NOT NULL,
    rbt12_proporcionalizado BOOLEAN         NOT NULL,
    -- A referencia a linha exata da tabela e o que torna a apuracao auditavel.
    faixa_tabela_id         BIGINT          NOT NULL REFERENCES faixa_tabela (id),
    aliquota_efetiva        NUMERIC(12, 10) NOT NULL,
    valor_das               NUMERIC(15, 2)  NOT NULL,
    apurado_em              TIMESTAMP       NOT NULL,
    CONSTRAINT uk_apuracao_empresa_competencia UNIQUE (empresa_id, ano, mes)
);
